# Generated by Django 4.1.7 on 2023-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='auctions/static/images/User01.jpg', upload_to='user_profiles'),
        ),
    ]
