# Generated by Django 4.1.7 on 2023-03-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='auctions/static/User01.png', upload_to='user_profiles'),
        ),
    ]
