# Generated by Django 4.1.7 on 2023-03-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
