# Generated by Django 4.1.7 on 2023-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_photo',
        ),
    ]
