# Generated by Django 4.1.7 on 2023-03-30 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_comment_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
