# Generated by Django 4.1.7 on 2023-03-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_upvoters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CH', 'chairs'), ('CA', 'cabinets'), ('SO', 'sofas'), ('TA', 'tables'), ('DE', 'decor'), ('OT', 'others')], default='others', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=280),
        ),
    ]
